module.exports = {
  apps: [
    {
      name: 'strapi',
      cwd: '/home/deploy/ex-situ-clean/backend',
      script: 'npm',
      args: 'run start',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 1337,
        HOST: '127.0.0.1',
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '1G',
      error_file: '/home/deploy/.pm2/logs/strapi-error.log',
      out_file: '/home/deploy/.pm2/logs/strapi-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'nextjs',
      cwd: '/home/deploy/ex-situ-clean/frontend',
      interpreter: 'none',
      script: 'pnpm',
      args: 'start -p 3000 -H 127.0.0.1',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: '1G',
      error_file: '/home/deploy/.pm2/logs/nextjs-error.log',
      out_file: '/home/deploy/.pm2/logs/nextjs-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
