// ─────────────────────────────────────────────────────────────────────────────
// Aura Design System — Generated Token File
// ⚡ Local-First: Your tokens, your code, no external cloud required.
// Auto-generated by Aura Orchestrator on 2026-03-27. Do not edit manually.
// ─────────────────────────────────────────────────────────────────────────────
export const tokens = {
  "colors": {
    "blue-50": "#EFF6FF", // Lightest blue tint
    "blue-100": "#DBEAFE", // Light blue
    "blue-500": "#3B82F6", // Primary brand blue
    "blue-600": "#2563EB", // Hover state blue
    "blue-900": "#1E3A8A", // Darkest blue
    "gray-50": "#F9FAFB", // Surface background
    "gray-100": "#F3F4F6", // Subtle background
    "gray-700": "#374151", // Secondary text
    "gray-900": "#111827", // Primary text
    "white": "#FFFFFF", // Pure white
    "success": "#10B981", // Success / positive
    "danger": "#EF4444", // Error / destructive
    "warning": "#F59E0B", // Warning state
    "jj": "#3B82F6", // jj
    "ds-color-bg-base": "#ffffff", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-overlay": "hsla(0, 0%, 100%, 0.5)", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-scrim": "rgba(0, 0, 0, 0.25)", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-gallery-overlay": "rgba(0, 0, 0, 0.7)", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-panel-backdrop": "rgba(229, 229, 229, 0.9)", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-surface-subtle": "rgba(249, 250, 251, 0.5)", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-error": "#fef2f2", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-hover": "#f9fafb", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-selected-blue": "#eff6ff", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-selected-amber": "#fffbeb", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-chip-orange": "#fff7ed", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-link-card-hover": "#f5f5f5", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-violet": "rgba(245, 243, 255, 0.5)", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-path-country": "#dbeafe", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-path-city": "#d1fae5", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-path-institution": "#fef3c7", // CSS variable from frontend/styles/tokens.css
    "ds-color-bg-path-default": "#f3f4f6", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-primary": "#000000", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-foreground": "hsl(222.2, 84%, 4.9%)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-muted": "hsl(215.4, 16.3%, 46.9%)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-secondary": "#9ca3af", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-tertiary": "#6b7280", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-panel-muted": "hsl(0, 0%, 45%)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-selected-blue": "#1e40af", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-chip-blue": "#1d4ed8", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-selected-orange": "#9a3412", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-chip-orange": "#c2410c", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-faint": "#d1d5db", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-breadcrumb-separator": "rgba(0, 0, 0, 0.4)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-breadcrumb-inactive": "rgba(0, 0, 0, 0.6)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-error": "#ef4444", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-indigo": "#4f46e5", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-violet": "#7c3aed", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-path-country": "#1d4ed8", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-path-city": "#047857", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-path-institution": "#b45309", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-path-default": "#4b5563", // CSS variable from frontend/styles/tokens.css
    "ds-color-border-default": "hsl(214.3, 31.8%, 91.4%)", // CSS variable from frontend/styles/tokens.css
    "ds-color-border-subtle": "#f3f4f6", // CSS variable from frontend/styles/tokens.css
    "ds-color-border-light": "#e5e7eb", // CSS variable from frontend/styles/tokens.css
    "ds-color-border-focus-blue": "#bfdbfe", // CSS variable from frontend/styles/tokens.css
    "ds-color-border-ring-blue": "#3b82f6", // CSS variable from frontend/styles/tokens.css
    "ds-color-border-ring-amber": "#fde68a", // CSS variable from frontend/styles/tokens.css
    "ds-color-border-map-control": "rgba(0, 0, 0, 0.1)", // CSS variable from frontend/styles/tokens.css
    "ds-color-accent-orange": "#f97316", // CSS variable from frontend/styles/tokens.css
    "ds-color-accent-blue": "#3b82f6", // CSS variable from frontend/styles/tokens.css
    "ds-color-state-hover-blue": "#dbeafe", // CSS variable from frontend/styles/tokens.css
    "ds-color-state-hover-orange": "#ffedd5", // CSS variable from frontend/styles/tokens.css
    "ds-color-state-alert-bg": "#ef4444", // CSS variable from frontend/styles/tokens.css
    "ds-color-state-destructive": "hsl(0, 84.2%, 60.2%)", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-arc-selected": "rgba(59, 130, 246, 1)", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-arc-selected-target": "rgba(147, 51, 234, 1)", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-highlight": "rgba(59, 130, 246, 1)", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-wiki-fill": "rgba(99, 102, 241, 0.78)", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-wiki-highlight": "rgba(139, 92, 246, 1)", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-wiki-stroke": "#ffffff", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-dot-country": "#3b82f6", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-dot-city": "#10b981", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-dot-institution": "#f59e0b", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-dot-default": "#6b7280", // CSS variable from frontend/styles/tokens.css
    "ds-color-map-tooltip-bg": "rgba(0, 0, 0, 0.85)", // CSS variable from frontend/styles/tokens.css
    "padding": "2rem", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "border": "hsl(var(--border))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "input": "hsl(var(--input))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "ring": "hsl(var(--ring))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "background": "hsl(var(--background))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "DEFAULT": "hsl(var(--primary))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--primary-foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "DEFAULT": "hsl(var(--secondary))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--secondary-foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "DEFAULT": "hsl(var(--destructive))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--destructive-foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "DEFAULT": "hsl(var(--muted))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--muted-foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "DEFAULT": "hsl(var(--accent))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--accent-foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "DEFAULT": "hsl(var(--popover))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--popover-foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "DEFAULT": "hsl(var(--card))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--card-foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "DEFAULT": "hsl(var(--sidebar-background))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "foreground": "hsl(var(--sidebar-foreground))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "primary": "hsl(var(--sidebar-primary))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "accent": "hsl(var(--sidebar-accent))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "border": "hsl(var(--sidebar-border))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "ring": "hsl(var(--sidebar-ring))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "1": "hsl(var(--chart-1))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "2": "hsl(var(--chart-2))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "3": "hsl(var(--chart-3))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "4": "hsl(var(--chart-4))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "5": "hsl(var(--chart-5))", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "height": "var(--radix-accordion-content-height)", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "height": "0", // Imported from frontend/lib/design-system/tailwind.config.tokens.ts
    "bgBase": "#ffffff", // Imported from frontend/lib/design-system/tokens.ts
    "bgOverlay": "hsla(0, 0%, 100%, 0.5)", // Imported from frontend/lib/design-system/tokens.ts
    "bgScrim": "rgba(0, 0, 0, 0.25)", // Imported from frontend/lib/design-system/tokens.ts
    "bgGalleryOverlay": "rgba(0, 0, 0, 0.7)", // Imported from frontend/lib/design-system/tokens.ts
    "bgPanelBackdrop": "rgba(229, 229, 229, 0.9)", // Imported from frontend/lib/design-system/tokens.ts
    "bgSurfaceSubtle": "rgba(249, 250, 251, 0.5)", // Imported from frontend/lib/design-system/tokens.ts
    "bgError": "#fef2f2", // Imported from frontend/lib/design-system/tokens.ts
    "bgHover": "#f9fafb", // Imported from frontend/lib/design-system/tokens.ts
    "bgSelectedBlue": "#eff6ff", // Imported from frontend/lib/design-system/tokens.ts
    "bgSelectedAmber": "#fffbeb", // Imported from frontend/lib/design-system/tokens.ts
    "bgChipOrange": "#fff7ed", // Imported from frontend/lib/design-system/tokens.ts
    "bgLinkCardHover": "#f5f5f5", // Imported from frontend/lib/design-system/tokens.ts
    "bgViolet": "rgba(245, 243, 255, 0.5)", // Imported from frontend/lib/design-system/tokens.ts
    "bgPathCountry": "#dbeafe", // Imported from frontend/lib/design-system/tokens.ts
    "bgPathCity": "#d1fae5", // Imported from frontend/lib/design-system/tokens.ts
    "bgPathInstitution": "#fef3c7", // Imported from frontend/lib/design-system/tokens.ts
    "bgPathDefault": "#f3f4f6", // Imported from frontend/lib/design-system/tokens.ts
    "textPrimary": "#000000", // Imported from frontend/lib/design-system/tokens.ts
    "textForeground": "hsl(222.2, 84%, 4.9%)", // Imported from frontend/lib/design-system/tokens.ts
    "textMuted": "hsl(215.4, 16.3%, 46.9%)", // Imported from frontend/lib/design-system/tokens.ts
    "textSecondary": "#9ca3af", // Imported from frontend/lib/design-system/tokens.ts
    "textTertiary": "#6b7280", // Imported from frontend/lib/design-system/tokens.ts
    "textPanelMuted": "hsl(0, 0%, 45%)", // Imported from frontend/lib/design-system/tokens.ts
    "textSelectedBlue": "#1e40af", // Imported from frontend/lib/design-system/tokens.ts
    "textChipBlue": "#1d4ed8", // Imported from frontend/lib/design-system/tokens.ts
    "textSelectedOrange": "#9a3412", // Imported from frontend/lib/design-system/tokens.ts
    "textChipOrange": "#c2410c", // Imported from frontend/lib/design-system/tokens.ts
    "textFaint": "#d1d5db", // Imported from frontend/lib/design-system/tokens.ts
    "textBreadcrumbSeparator": "rgba(0, 0, 0, 0.4)", // Imported from frontend/lib/design-system/tokens.ts
    "textBreadcrumbInactive": "rgba(0, 0, 0, 0.6)", // Imported from frontend/lib/design-system/tokens.ts
    "textError": "#ef4444", // Imported from frontend/lib/design-system/tokens.ts
    "textIndigo": "#4f46e5", // Imported from frontend/lib/design-system/tokens.ts
    "textViolet": "#7c3aed", // Imported from frontend/lib/design-system/tokens.ts
    "textPathCountry": "#1d4ed8", // Imported from frontend/lib/design-system/tokens.ts
    "textPathCity": "#047857", // Imported from frontend/lib/design-system/tokens.ts
    "textPathInstitution": "#b45309", // Imported from frontend/lib/design-system/tokens.ts
    "textPathDefault": "#4b5563", // Imported from frontend/lib/design-system/tokens.ts
    "borderDefault": "hsl(214.3, 31.8%, 91.4%)", // Imported from frontend/lib/design-system/tokens.ts
    "borderSubtle": "#f3f4f6", // Imported from frontend/lib/design-system/tokens.ts
    "borderLight": "#e5e7eb", // Imported from frontend/lib/design-system/tokens.ts
    "borderFocusBlue": "#bfdbfe", // Imported from frontend/lib/design-system/tokens.ts
    "borderRingBlue": "#3b82f6", // Imported from frontend/lib/design-system/tokens.ts
    "borderRingAmber": "#fde68a", // Imported from frontend/lib/design-system/tokens.ts
    "borderMapControl": "rgba(0, 0, 0, 0.1)", // Imported from frontend/lib/design-system/tokens.ts
    "accentOrange": "#f97316", // Imported from frontend/lib/design-system/tokens.ts
    "accentBlue": "#3b82f6", // Imported from frontend/lib/design-system/tokens.ts
    "stateHoverBlue": "#dbeafe", // Imported from frontend/lib/design-system/tokens.ts
    "stateHoverOrange": "#ffedd5", // Imported from frontend/lib/design-system/tokens.ts
    "stateAlertBg": "#ef4444", // Imported from frontend/lib/design-system/tokens.ts
    "stateDestructive": "hsl(0, 84.2%, 60.2%)", // Imported from frontend/lib/design-system/tokens.ts
    "mapArcSelected": "rgba(59, 130, 246, 1)", // Imported from frontend/lib/design-system/tokens.ts
    "mapArcSelectedTarget": "rgba(147, 51, 234, 1)", // Imported from frontend/lib/design-system/tokens.ts
    "mapHighlight": "rgba(59, 130, 246, 1)", // Imported from frontend/lib/design-system/tokens.ts
    "mapWikiFill": "rgba(99, 102, 241, 0.78)", // Imported from frontend/lib/design-system/tokens.ts
    "mapWikiHighlight": "rgba(139, 92, 246, 1)", // Imported from frontend/lib/design-system/tokens.ts
    "mapWikiStroke": "#ffffff", // Imported from frontend/lib/design-system/tokens.ts
    "mapDotCountry": "#3b82f6", // Imported from frontend/lib/design-system/tokens.ts
    "mapDotCity": "#10b981", // Imported from frontend/lib/design-system/tokens.ts
    "mapDotInstitution": "#f59e0b", // Imported from frontend/lib/design-system/tokens.ts
    "mapDotDefault": "#6b7280", // Imported from frontend/lib/design-system/tokens.ts
    "mapTooltipBg": "rgba(0, 0, 0, 0.85)", // Imported from frontend/lib/design-system/tokens.ts
    "backgroundColor-rgba(0": "rgba(0", // Inline style in frontend/components/image-gallery.tsx
    "backgroundColor-white": "white", // Inline style in frontend/components/image-gallery.tsx
    "color-black": "black", // Inline style in frontend/components/image-gallery.tsx
    "color-#666": "#666", // Inline style in frontend/components/image-gallery.tsx
    "color-var(--panel-text-muted": "var(--panel-text-muted", // Inline style in frontend/components/image-gallery.tsx
    "color-#999": "#999", // Inline style in frontend/components/image-gallery.tsx
    "color-#2a2a2a": "#2a2a2a", // Inline style in frontend/components/image-gallery.tsx
    "color-#444": "#444", // Inline style in frontend/components/map/map-view.tsx
    "backgroundColor-item.color": "item.color", // Inline style in frontend/components/ui/chart.tsx
    "#666": "#666", // Inline color from frontend/components/image-gallery.tsx
    "#999": "#999", // Inline color from frontend/components/image-gallery.tsx
    "#2a2a2a": "#2a2a2a", // Inline color from frontend/components/image-gallery.tsx
    "#fff": "#fff", // Inline color from frontend/components/map/map-view.tsx
    "#333": "#333", // Inline color from frontend/components/map/map-view.tsx
    "#000": "#000", // Inline color from frontend/components/map/map-view.tsx
    "#555": "#555", // Inline color from frontend/components/map/map-view.tsx
    "#444": "#444", // Inline color from frontend/components/map/map-view.tsx
    "#ccc": "#ccc", // Inline color from frontend/components/ui/chart.tsx
    "#111111": "#111111", // Inline color from frontend/lib/protomaps-dark-style.ts
    "text-gray-400": "text-gray-400", // text-gray-400 used 104× in 155 component-scan
    "text-gray-300": "text-gray-300", // text-gray-300 used 47× in 155 component-scan
    "bg-gray-50": "bg-gray-50", // bg-gray-50 used 44× in 155 component-scan
    "text-gray-500": "text-gray-500", // text-gray-500 used 42× in 155 component-scan
    "bg-blue-50": "bg-blue-50", // bg-blue-50 used 20× in 155 component-scan
    "border-gray-100": "border-gray-100", // border-gray-100 used 18× in 155 component-scan
    "bg-gray-100": "bg-gray-100", // bg-gray-100 used 15× in 155 component-scan
    "text-red-500": "text-red-500", // text-red-500 used 14× in 155 component-scan
    "text-gray-600": "text-gray-600", // text-gray-600 used 14× in 155 component-scan
    "text-blue-600": "text-blue-600", // text-blue-600 used 12× in 155 component-scan
  },
  "typography": {
    "text-xs": "12px", // Extra small body copy
    "text-sm": "14px", // Small body copy
    "text-base": "16px", // Default body size
    "text-lg": "18px", // Large body / small heading
    "text-xl": "20px", // Display small
    "text-2xl": "24px", // Section heading
    "text-4xl": "36px", // Page title
    "text-hero": "56px", // Hero / editorial headline
    "panel-text-muted": "0 0% 45%", // CSS variable from frontend/app/globals.css
    "ds-color-text-primary": "#000000", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-foreground": "hsl(222.2, 84%, 4.9%)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-muted": "hsl(215.4, 16.3%, 46.9%)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-secondary": "#9ca3af", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-tertiary": "#6b7280", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-panel-muted": "hsl(0, 0%, 45%)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-selected-blue": "#1e40af", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-chip-blue": "#1d4ed8", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-selected-orange": "#9a3412", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-chip-orange": "#c2410c", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-faint": "#d1d5db", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-breadcrumb-separator": "rgba(0, 0, 0, 0.4)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-breadcrumb-inactive": "rgba(0, 0, 0, 0.6)", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-error": "#ef4444", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-indigo": "#4f46e5", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-violet": "#7c3aed", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-path-country": "#1d4ed8", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-path-city": "#047857", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-path-institution": "#b45309", // CSS variable from frontend/styles/tokens.css
    "ds-color-text-path-default": "#4b5563", // CSS variable from frontend/styles/tokens.css
    "ds-font-size-base": "0.875rem", // CSS variable from frontend/styles/tokens.css
    "ds-font-size-body-md": "0.875rem", // CSS variable from frontend/styles/tokens.css
    "ds-font-size-caption": "10px", // CSS variable from frontend/styles/tokens.css
    "ds-font-size-micro": "9px", // CSS variable from frontend/styles/tokens.css
    "ds-font-size-label": "0.875rem", // CSS variable from frontend/styles/tokens.css
    "fontFamily": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, ", // Imported from frontend/lib/design-system/tokens.ts
    "fontSizeBase": "0.875rem", // Imported from frontend/lib/design-system/tokens.ts
    "fontSize": "0.875rem", // Imported from frontend/lib/design-system/tokens.ts
    "lineHeight": "1.25rem", // Imported from frontend/lib/design-system/tokens.ts
    "fontSize": "10px", // Imported from frontend/lib/design-system/tokens.ts
    "lineHeight": "1", // Imported from frontend/lib/design-system/tokens.ts
    "fontSize": "9px", // Imported from frontend/lib/design-system/tokens.ts
    "textTransform": "uppercase", // Imported from frontend/lib/design-system/tokens.ts
    "letterSpacing": "0.05em", // Imported from frontend/lib/design-system/tokens.ts
    "fontWeightNormal": "400", // Imported from frontend/lib/design-system/tokens.ts
    "fontWeightMedium": "500", // Imported from frontend/lib/design-system/tokens.ts
    "fontWeight": "500", // Imported from frontend/lib/design-system/tokens.ts
    "text-3xl": "30px", // text-3xl used 1× across components
  },
  "spacing": {
    "spacing-1": "4px", // 1 unit  (4px)
    "spacing-2": "18px", // 2 units (8px)
    "spacing-3": "12px", // 3 units (12px)
    "spacing-4": "16px", // 4 units (16px)
    "spacing-6": "24px", // 6 units (24px)
    "spacing-8": "32px", // 8 units (32px)
    "spacing-12": "48px", // 12 units (48px)
    "spacing-16": "64px", // 16 units (64px)
    "ds-space-0": "0px", // CSS variable from frontend/styles/tokens.css
    "ds-space-px": "1px", // CSS variable from frontend/styles/tokens.css
    "ds-space-0-5": "0.125rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-1": "0.25rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-1-5": "0.375rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-2": "0.5rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-2-5": "0.625rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-3": "0.75rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-4": "1rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-5": "1.25rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-6": "1.5rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-8": "2rem", // CSS variable from frontend/styles/tokens.css
    "ds-space-10": "2.5rem", // CSS variable from frontend/styles/tokens.css
    "ds-layout-grid-gap": "0.75rem", // CSS variable from frontend/styles/tokens.css
    "0": "0px", // Imported from frontend/lib/design-system/tokens.ts
    "px": "1px", // Imported from frontend/lib/design-system/tokens.ts
    "0.5": "0.125rem", // Imported from frontend/lib/design-system/tokens.ts
    "1": "0.25rem", // Imported from frontend/lib/design-system/tokens.ts
    "1.5": "0.375rem", // Imported from frontend/lib/design-system/tokens.ts
    "2": "0.5rem", // Imported from frontend/lib/design-system/tokens.ts
    "2.5": "0.625rem", // Imported from frontend/lib/design-system/tokens.ts
    "3": "0.75rem", // Imported from frontend/lib/design-system/tokens.ts
    "4": "1rem", // Imported from frontend/lib/design-system/tokens.ts
    "5": "1.25rem", // Imported from frontend/lib/design-system/tokens.ts
    "6": "1.5rem", // Imported from frontend/lib/design-system/tokens.ts
    "8": "2rem", // Imported from frontend/lib/design-system/tokens.ts
    "10": "2.5rem", // Imported from frontend/lib/design-system/tokens.ts
    "left": "20", // Imported from frontend/lib/design-system/tokens.ts
    "padding-isMobile ? 16px": "isMobile ? 16px", // Inline style in frontend/components/image-gallery.tsx
    "marginLeft-8px": "8px", // Inline style in frontend/components/image-gallery.tsx
    "gap-8px": "8px", // Inline style in frontend/components/image-gallery.tsx
    "padding-8px 16px": "8px 16px", // Inline style in frontend/components/image-gallery.tsx
    "gap-16px": "16px", // Inline style in frontend/components/image-gallery.tsx
    "padding-4px 16px 6px": "4px 16px 6px", // Inline style in frontend/components/image-gallery.tsx
    "gap-2": "8px", // gap-2 used 65× across components
    "py-1.5": "6px", // py-1.5 used 46× across components
    "px-4": "16px", // px-4 used 45× across components
    "gap-1": "4px", // gap-1 used 44× across components
    "px-2": "8px", // px-2 used 40× across components
    "p-1": "4px", // p-1 used 34× across components
    "gap-3": "12px", // gap-3 used 29× across components
    "px-3": "12px", // px-3 used 27× across components
    "mt-1": "4px", // mt-1 used 26× across components
    "p-4": "16px", // p-4 used 26× across components
    "py-0.5": "2px", // py-0.5 used 26× across components
    "p-2": "8px", // p-2 used 26× across components
    "py-2": "8px", // py-2 used 23× across components
    "px-1": "4px", // px-1 used 23× across components
    "mb-2": "8px", // mb-2 used 22× across components
    "p-0": "0px", // p-0 used 21× across components
    "ml-2": "8px", // ml-2 used 20× across components
    "p-3": "12px", // p-3 used 17× across components
    "py-4": "16px", // py-4 used 17× across components
    "pl-8": "32px", // pl-8 used 17× across components
  },
  "borderRadius": {
    "radius-none": "38px", // No rounding
    "radius-sm": "4px", // Subtle rounding
    "radius-md": "8px", // Default card radius
    "radius-lg": "12px", // Panels & modals
    "radius-xl": "16px", // Large containers
    "radius-full": "9999px", // Pill / badge shape
    "ds-radius-sm": "calc(0.5rem - 4px)", // CSS variable from frontend/styles/tokens.css
    "ds-radius-md": "calc(0.5rem - 2px)", // CSS variable from frontend/styles/tokens.css
    "ds-radius-lg": "0.5rem", // CSS variable from frontend/styles/tokens.css
    "ds-radius-tile": "10px", // CSS variable from frontend/styles/tokens.css
    "ds-radius-panel": "1rem", // CSS variable from frontend/styles/tokens.css
    "ds-radius-palette": "1.25rem", // CSS variable from frontend/styles/tokens.css
    "ds-radius-popup": "1rem", // CSS variable from frontend/styles/tokens.css
    "ds-radius-control": "6px", // CSS variable from frontend/styles/tokens.css
    "ds-radius-full": "9999px", // CSS variable from frontend/styles/tokens.css
    "sm": "calc(0.5rem - 4px)", // Imported from frontend/lib/design-system/tokens.ts
    "md": "calc(0.5rem - 2px)", // Imported from frontend/lib/design-system/tokens.ts
    "lg": "0.5rem", // Imported from frontend/lib/design-system/tokens.ts
    "tile": "10px", // Imported from frontend/lib/design-system/tokens.ts
    "panel": "1rem", // Imported from frontend/lib/design-system/tokens.ts
    "palette": "1.25rem", // Imported from frontend/lib/design-system/tokens.ts
    "popup": "1rem", // Imported from frontend/lib/design-system/tokens.ts
    "control": "6px", // Imported from frontend/lib/design-system/tokens.ts
    "full": "9999px", // Imported from frontend/lib/design-system/tokens.ts
    "borderRadius-inherit": "inherit", // Inline style in frontend/components/image-gallery.tsx
    "rounded-md": "6px", // rounded-md used 81× across components
    "rounded": "4px", // rounded used 48× across components
    "rounded-lg": "8px", // rounded-lg used 39× across components
    "rounded-full": "9999px", // rounded-full used 35× across components
    "rounded-sm": "2px", // rounded-sm used 19× across components
    "rounded-2xl": "16px", // rounded-2xl used 11× across components
    "rounded-xl": "12px", // rounded-xl used 1× across components
  },
  "shadows": {
    "shadow-xs": "0 1px 2px rgba(0,0,0,0.05)", // Hair light shadow
    "shadow-sm": "0 1px 3px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.06)", // Small elevation
    "shadow-md": "0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.06)", // Card shadow
    "shadow-lg": "0 10px 15px rgba(0,0,0,0.1), 0 4px 6px rgba(0,0,0,0.05)", // Modal shadow
    "shadow-xl": "0 20px 25px rgba(0,0,0,0.15), 0 10px 10px rgba(0,0,0,0.04)", // Flyout shadow
    "ds-shadow-lg": "0 10px 15px -3px rgba(0, 0, 0, 0.1),\n    0 4px 6px -4px rgba(0, 0, 0, 0.1)", // CSS variable from frontend/styles/tokens.css
    "ds-shadow-2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)", // CSS variable from frontend/styles/tokens.css
    "ds-shadow-xl": "0 20px 25px -5px rgba(0, 0, 0, 0.1),\n    0 8px 10px -6px rgba(0, 0, 0, 0.1)", // CSS variable from frontend/styles/tokens.css
    "ds-shadow-control": "0 2px 6px rgba(0, 0, 0, 0.1)", // CSS variable from frontend/styles/tokens.css
    "ds-shadow-tooltip": "0 2px 10px rgba(0, 0, 0, 0.3)", // CSS variable from frontend/styles/tokens.css
    "ds-shadow-subtle": "0 1px 3px rgba(0, 0, 0, 0.05)", // CSS variable from frontend/styles/tokens.css
    "ds-shadow-gallery": "0 10px 25px -5px rgba(0, 0, 0, 0.1),\n    0 10px 10px -5px rgba(0, 0, 0, 0.04)", // CSS variable from frontend/styles/tokens.css
    "ds-shadow-dropdown": "0 4px 12px rgba(0, 0, 0, 0.15)", // CSS variable from frontend/styles/tokens.css
    "lg": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)", // Imported from frontend/lib/design-system/tokens.ts
    "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)", // Imported from frontend/lib/design-system/tokens.ts
    "xl": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)", // Imported from frontend/lib/design-system/tokens.ts
    "control": "0 2px 6px rgba(0, 0, 0, 0.1)", // Imported from frontend/lib/design-system/tokens.ts
    "tooltip": "0 2px 10px rgba(0, 0, 0, 0.3)", // Imported from frontend/lib/design-system/tokens.ts
    "subtle": "0 1px 3px rgba(0, 0, 0, 0.05)", // Imported from frontend/lib/design-system/tokens.ts
    "gallery": "0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)", // Imported from frontend/lib/design-system/tokens.ts
    "dropdown": "0 4px 12px rgba(0, 0, 0, 0.15)", // Imported from frontend/lib/design-system/tokens.ts
  },
  "opacity": {
    "opacity-0": "0", // Fully transparent
    "opacity-25": "0.25", // 25% visible
    "opacity-50": "0.5", // 50% visible
    "opacity-75": "0.75", // 75% visible
    "opacity-100": "1", // Fully opaque
  },
  "layout": {
    "panelWidthDefault": "40%", // Imported from frontend/lib/design-system/tokens.ts
    "panelWidthExpanded": "calc(100% - 5rem)", // Imported from frontend/lib/design-system/tokens.ts
    "panelHeightExpanded": "calc(100vh - 5rem)", // Imported from frontend/lib/design-system/tokens.ts
    "panelInsetDesktop": "2.5rem", // Imported from frontend/lib/design-system/tokens.ts
    "mobileSheetDefault": "40%", // Imported from frontend/lib/design-system/tokens.ts
    "mobileSheetExpanded": "100%", // Imported from frontend/lib/design-system/tokens.ts
    "mobileSheetMinimized": "auto", // Imported from frontend/lib/design-system/tokens.ts
    "mobileSheetInset": "20px", // Imported from frontend/lib/design-system/tokens.ts
    "headerPanelWidth": "20rem", // Imported from frontend/lib/design-system/tokens.ts
    "headerPanelInset": "2.5rem", // Imported from frontend/lib/design-system/tokens.ts
    "commandPaletteMaxWidth": "32rem", // Imported from frontend/lib/design-system/tokens.ts
    "commandPaletteTopOffset": "15vh", // Imported from frontend/lib/design-system/tokens.ts
    "commandPaletteMaxHeight": "50vh", // Imported from frontend/lib/design-system/tokens.ts
    "mapControlInset": "40px", // Imported from frontend/lib/design-system/tokens.ts
    "gridTileHeight": "11rem", // Imported from frontend/lib/design-system/tokens.ts
    "gridImageMaxHeight": "9rem", // Imported from frontend/lib/design-system/tokens.ts
    "gridGap": "0.75rem", // Imported from frontend/lib/design-system/tokens.ts
    "containerMax2xl": "1400px", // Imported from frontend/lib/design-system/tokens.ts
    "fullscreen": "grid-cols-2 xs:grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 xl:grid-cols-7 2xl:grid-cols-8", // Imported from frontend/lib/design-system/tokens.ts
    "default40": "grid-cols-3 xs:grid-cols-3 sm:grid-cols-3 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-3", // Imported from frontend/lib/design-system/tokens.ts
    "default50": "grid-cols-3 xs:grid-cols-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-4 xl:grid-cols-4 2xl:grid-cols-4", // Imported from frontend/lib/design-system/tokens.ts
    "listMaxHeight": "10rem", // Imported from frontend/lib/design-system/tokens.ts
    "wikiPopupWidth": "300px", // Imported from frontend/lib/design-system/tokens.ts
    "linkCardHeight": "11rem", // Imported from frontend/lib/design-system/tokens.ts
    "left": "20", // Imported from frontend/lib/design-system/tokens.ts
    "linkCardColumns": "3", // Imported from frontend/lib/design-system/tokens.ts
  },
  "backdrop": {
    "panel": "blur(8px)", // Imported from frontend/lib/design-system/tokens.ts
    "resizable": "blur(4px)", // Imported from frontend/lib/design-system/tokens.ts
    "scrim": "blur(2px)", // Imported from frontend/lib/design-system/tokens.ts
    "popover": "blur(12px)", // Imported from frontend/lib/design-system/tokens.ts
  },
  "motion": {
    "duration": "150ms", // Imported from frontend/lib/design-system/tokens.ts
    "easing": "ease", // Imported from frontend/lib/design-system/tokens.ts
    "duration": "300ms", // Imported from frontend/lib/design-system/tokens.ts
    "easing": "ease-in-out", // Imported from frontend/lib/design-system/tokens.ts
    "duration": "500ms", // Imported from frontend/lib/design-system/tokens.ts
    "easing": "ease-out", // Imported from frontend/lib/design-system/tokens.ts
    "duration": "200ms", // Imported from frontend/lib/design-system/tokens.ts
    "duration": "1500ms", // Imported from frontend/lib/design-system/tokens.ts
    "easing": "linear", // Imported from frontend/lib/design-system/tokens.ts
    "iterationCount": "infinite", // Imported from frontend/lib/design-system/tokens.ts
    "detail": "(t: number) => 1 - Math.pow(1 - t, 2.2)", // Imported from frontend/lib/design-system/tokens.ts
    "levelShift": "(t: number) => 1 - Math.pow(1 - t, 3.2)", // Imported from frontend/lib/design-system/tokens.ts
    "duration": "300", // Imported from frontend/lib/design-system/tokens.ts
    "fast": "800", // Imported from frontend/lib/design-system/tokens.ts
    "default": "1200", // Imported from frontend/lib/design-system/tokens.ts
    "slow": "1400", // Imported from frontend/lib/design-system/tokens.ts
    "levelShift": "2300", // Imported from frontend/lib/design-system/tokens.ts
  },
  "zIndex": {
    "mapCanvas": "2", // Imported from frontend/lib/design-system/tokens.ts
    "map": "1", // Imported from frontend/lib/design-system/tokens.ts
    "mapControls": "10", // Imported from frontend/lib/design-system/tokens.ts
    "panel": "20", // Imported from frontend/lib/design-system/tokens.ts
    "panelHeader": "30", // Imported from frontend/lib/design-system/tokens.ts
    "mapOverlay": "40", // Imported from frontend/lib/design-system/tokens.ts
    "tooltip": "50", // Imported from frontend/lib/design-system/tokens.ts
    "gallery": "60", // Imported from frontend/lib/design-system/tokens.ts
    "mapPopup": "60", // Imported from frontend/lib/design-system/tokens.ts
    "alert": "70", // Imported from frontend/lib/design-system/tokens.ts
    "commandPalette": "80", // Imported from frontend/lib/design-system/tokens.ts
    "dropdown": "1000", // Imported from frontend/lib/design-system/tokens.ts
  },
  "breakpoints": {
    "xs": "480px", // Imported from frontend/lib/design-system/tokens.ts
    "sm": "640px", // Imported from frontend/lib/design-system/tokens.ts
    "md": "768px", // Imported from frontend/lib/design-system/tokens.ts
    "lg": "1024px", // Imported from frontend/lib/design-system/tokens.ts
    "xl": "1280px", // Imported from frontend/lib/design-system/tokens.ts
    "2xl": "1400px", // Imported from frontend/lib/design-system/tokens.ts
  },
  "iconSizes": {
    "dot": "0.375rem", // Imported from frontend/lib/design-system/tokens.ts
    "xs": "0.625rem", // Imported from frontend/lib/design-system/tokens.ts
    "sm": "0.875rem", // Imported from frontend/lib/design-system/tokens.ts
    "md": "1rem", // Imported from frontend/lib/design-system/tokens.ts
    "searchBar": "18px", // Imported from frontend/lib/design-system/tokens.ts
    "lg": "1.25rem", // Imported from frontend/lib/design-system/tokens.ts
    "xl": "2rem", // Imported from frontend/lib/design-system/tokens.ts
    "2xl": "3rem", // Imported from frontend/lib/design-system/tokens.ts
    "mapControl": "15px", // Imported from frontend/lib/design-system/tokens.ts
    "mapControlButton": "28px", // Imported from frontend/lib/design-system/tokens.ts
    "panelToggle": "18px", // Imported from frontend/lib/design-system/tokens.ts
  },
  "iconRegistry": {
    "component": "IconClose", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/close.svg", // Imported from frontend/lib/design-system/tokens.ts
    "component": "IconSearch", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/search.svg", // Imported from frontend/lib/design-system/tokens.ts
    "component": "IconDownloadCsv", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/download-csv.svg", // Imported from frontend/lib/design-system/tokens.ts
    "component": "IconExpand", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/expand.svg", // Imported from frontend/lib/design-system/tokens.ts
    "component": "IconMinimize", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/minimize.svg", // Imported from frontend/lib/design-system/tokens.ts
    "component": "IconPanelClosed", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/object-panel-closed.svg", // Imported from frontend/lib/design-system/tokens.ts
    "component": "IconPanelOpen", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/object-panel-open.svg", // Imported from frontend/lib/design-system/tokens.ts
    "component": "IconShare", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/share.svg", // Imported from frontend/lib/design-system/tokens.ts
    "component": "IconSource", // Imported from frontend/lib/design-system/tokens.ts
    "file": "/icons/source.svg", // Imported from frontend/lib/design-system/tokens.ts
    "App": "component-styles", // Imported from tokens.ts
    "Admin": "component-styles", // Imported from tokens.ts
    "Api": "component-styles", // Imported from tokens.ts
    "Database": "component-styles", // Imported from tokens.ts
    "Ecosystem.config": "component-styles", // Imported from tokens.ts
    "Middlewares": "component-styles", // Imported from tokens.ts
    "Plugins": "component-styles", // Imported from tokens.ts
    "Server": "component-styles", // Imported from tokens.ts
    "COLLECTION": "component-styles", // Imported from tokens.ts
    "ImportData": "component-styles", // Imported from tokens.ts
    "PublishEntries": "component-styles", // Imported from tokens.ts
    "SetupPostGIS": "component-styles", // Imported from tokens.ts
    "SyncStrapiContent": "component-styles", // Imported from tokens.ts
    "UpdateImgUrlAntik": "component-styles", // Imported from tokens.ts
    "App.example": "component-styles", // Imported from tokens.ts
    "Webpack.config.example": "component-styles", // Imported from tokens.ts
    "Geocode": "component-styles", // Imported from tokens.ts
    "Stats": "component-styles", // Imported from tokens.ts
    "Webhook": "component-styles", // Imported from tokens.ts
    "CREATE": "component-styles", // Imported from tokens.ts
    "Components.d": "component-styles", // Imported from tokens.ts
    "ContentTypes.d": "component-styles", // Imported from tokens.ts
    "GET": "component-styles", // Imported from tokens.ts
    "PATCH": "component-styles", // Imported from tokens.ts
    "OPTIONS": "component-styles", // Imported from tokens.ts
    "ObjectPage": "min-h-screen bg-background sticky top-0 z-50 border-b", // Imported from tokens.ts
    "RootLayout": "component-styles", // Imported from tokens.ts
    "Loading": "component-styles", // Imported from tokens.ts
    "MapLayout": "h-screen flex flex-col bg-white overflow-hidden flex-1", // Imported from tokens.ts
    "MapPage": "flex h-full w-full items-center justify-center bg-white", // Imported from tokens.ts
    "RootPage": "component-styles", // Imported from tokens.ts
    "ArcDetailPage": "max-w-6xl mx-auto px-5 py-4 mb-4 flex", // Imported from tokens.ts
    "CollectionDetailPage": "max-w-5xl mx-auto px-5 py-4 mb-4 text-amber-500", // Imported from tokens.ts
    "ResearchLayout": "min-h-screen bg-white flex flex-col sticky top-0", // Imported from tokens.ts
    "ResearchPage": "max-w-5xl mx-auto px-5 py-4 flex items-center", // Imported from tokens.ts
    "ResolversLayout": "resolver-dashboard-root", // Imported from tokens.ts
    "ResolversPage": "component-styles", // Imported from tokens.ts
    "BackButton": "gap-2 h-4 w-4", // Imported from tokens.ts
    "BlurhashImage": "component-styles", // Imported from tokens.ts
    "ClientMapLibreCSS": "component-styles", // Imported from tokens.ts
    "FacetedFilter": "border-b border-border/50 last:border-b-0 pb-2 last:pb-0 w-full", // Imported from tokens.ts
    "Index": "h-4 w-4", // Imported from tokens.ts
    "ImageGallery": "shadow-lg h-8 w-8 h-4 w-4 gallery-image-bg", // Imported from tokens.ts
    "LazyImage": "relative overflow-hidden", // Imported from tokens.ts
    "V3CommandPalette": "fixed inset-0 z-[80] bg-black/25 backdrop-blur-[2px] flex", // Imported from tokens.ts
    "MapView": "w-full h-full flex items-center justify-center bg-red-50", // Imported from tokens.ts
    "ObjectPanel": "h-full flex flex-col flex-shrink-0 items-center justify-center", // Imported from tokens.ts
    "MapLibreCSS": "component-styles", // Imported from tokens.ts
    "ObjectGrid": "flex flex-col justify-center items-center h-full p-4", // Imported from tokens.ts
    "ObjectList": "flex flex-col gap-3 justify-center items-center h-full", // Imported from tokens.ts
    "Index": "component-styles", // Imported from tokens.ts
    "StatusChip": "h-[4px] bg-secondary rounded-full flex-1 overflow-hidden flex", // Imported from tokens.ts
    "ResolverDashboard": "h-screen flex flex-col items-center justify-center bg-background", // Imported from tokens.ts
    "ResolverList": "w-[260px] flex-shrink-0 border-r border-border bg-background flex", // Imported from tokens.ts
    "RightPanel": "w-[240px] flex-shrink-0 border-l border-border bg-background flex", // Imported from tokens.ts
    "TopBar": "flex items-center px-5 h-11 border-b border-border", // Imported from tokens.ts
    "Types": "component-styles", // Imported from tokens.ts
    "ThemeProvider": "component-styles", // Imported from tokens.ts
    "Accordion": "flex h-4 w-4 shrink-0 transition-transform duration-200", // Imported from tokens.ts
    "AlertDialog": "component-styles", // Imported from tokens.ts
    "Alert": "component-styles", // Imported from tokens.ts
    "AspectRatio": "component-styles", // Imported from tokens.ts
    "Avatar": "component-styles", // Imported from tokens.ts
    "Badge": "component-styles", // Imported from tokens.ts
    "Breadcrumb": "h-4 w-4 sr-only", // Imported from tokens.ts
    "Button": "component-styles", // Imported from tokens.ts
    "Calendar": "h-4 w-4", // Imported from tokens.ts
    "Card": "component-styles", // Imported from tokens.ts
    "CarouselContext": "overflow-hidden h-4 w-4 sr-only", // Imported from tokens.ts
    "THEMES": "grid gap-1.5 text-muted-foreground font-mono font-medium tabular-nums", // Imported from tokens.ts
    "Checkbox": "h-3 w-3", // Imported from tokens.ts
    "Collapsible": "component-styles", // Imported from tokens.ts
    "Command": "overflow-hidden p-0 shadow-lg [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground", // Imported from tokens.ts
    "ContextMenu": "ml-auto h-4 w-4 absolute left-2 flex", // Imported from tokens.ts
    "Dialog": "absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background", // Imported from tokens.ts
    "Drawer": "mx-auto mt-4 h-2 w-[100px] rounded-full bg-muted", // Imported from tokens.ts
    "DropdownMenu": "ml-auto absolute left-2 flex h-3.5 w-3.5", // Imported from tokens.ts
    "Form": "component-styles", // Imported from tokens.ts
    "HoverCard": "component-styles", // Imported from tokens.ts
    "InputOTP": "pointer-events-none absolute inset-0 flex items-center justify-center", // Imported from tokens.ts
    "Input": "component-styles", // Imported from tokens.ts
    "Label": "component-styles", // Imported from tokens.ts
    "MenubarMenu": "ml-auto h-4 w-4 absolute left-2 flex", // Imported from tokens.ts
    "NavigationMenu": "relative top-[1px] ml-1 h-3 w-3 transition", // Imported from tokens.ts
    "Pagination": "h-4 w-4 sr-only", // Imported from tokens.ts
    "Popover": "component-styles", // Imported from tokens.ts
    "Progress": "h-full w-full flex-1 bg-primary transition-all", // Imported from tokens.ts
    "RadioGroup": "flex items-center justify-center h-2.5 w-2.5 fill-current", // Imported from tokens.ts
    "ResizablePanelGroup": "z-10 flex h-4 w-3 items-center justify-center", // Imported from tokens.ts
    "ScrollArea": "h-full w-full rounded-[inherit] relative flex-1 rounded-full", // Imported from tokens.ts
    "Select": "h-4 w-4 opacity-50 absolute left-2 flex", // Imported from tokens.ts
    "Separator": "component-styles", // Imported from tokens.ts
    "Sheet": "absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background", // Imported from tokens.ts
    "SidebarContext": "w-[--sidebar-width] bg-sidebar p-0 text-sidebar-foreground [&>button]:hidden flex", // Imported from tokens.ts
    "Skeleton": "component-styles", // Imported from tokens.ts
    "Slider": "relative h-2 w-full grow overflow-hidden rounded-full", // Imported from tokens.ts
    "Toaster": "toaster group", // Imported from tokens.ts
    "Spinner": "component-styles", // Imported from tokens.ts
    "Switch": "component-styles", // Imported from tokens.ts
    "Table": "relative w-full overflow-auto", // Imported from tokens.ts
    "Tabs": "component-styles", // Imported from tokens.ts
    "Textarea": "component-styles", // Imported from tokens.ts
    "ToastProvider": "h-4 w-4", // Imported from tokens.ts
    "Toaster": "bg-white text-black border border-gray-200 shadow-md grid", // Imported from tokens.ts
    "ToggleGroupContext": "component-styles", // Imported from tokens.ts
    "Toggle": "component-styles", // Imported from tokens.ts
    "TooltipProvider": "component-styles", // Imported from tokens.ts
    "UnifiedSearchBox": "relative h-3.5 w-3.5 animate-spin rounded-full border-2", // Imported from tokens.ts
    "Components": "h-6 w-6 h-8 w-8 w-4 h-4", // Imported from tokens.ts
    "Tailwind.config.tokens": "component-styles", // Imported from tokens.ts
    "Tokens": "h-4 w-4", // Imported from tokens.ts
    "Utils": "component-styles", // Imported from tokens.ts
    "Next.config": "component-styles", // Imported from tokens.ts
    "Tailwind.config": "component-styles", // Imported from tokens.ts
    "Tokens": "component-styles", // Imported from tokens.ts
    "top": "0", // Imported from tokens.ts
  },
  "grids": {},
  "components": {
    "App": "component-styles", // Component defined in backend/.strapi/client/app.js
    "Admin": "component-styles", // Component defined in backend/config/admin.js
    "Api": "component-styles", // Component defined in backend/config/api.js
    "Database": "component-styles", // Component defined in backend/config/database.js
    "Ecosystem.config": "component-styles", // Component defined in backend/config/ecosystem.config.js
    "Middlewares": "component-styles", // Component defined in backend/config/middlewares.js
    "Plugins": "component-styles", // Component defined in backend/config/plugins.js
    "Server": "component-styles", // Component defined in backend/config/server.js
    "COLLECTION": "component-styles", // Component defined in backend/scripts/bulkUnpublishExcept.js
    "ImportData": "component-styles", // Component defined in backend/scripts/importData.js
    "Pre-strapi": "component-styles", // Component defined in backend/scripts/pre-strapi.js
    "PublishEntries": "component-styles", // Component defined in backend/scripts/publishEntries.js
    "SetupPostGIS": "component-styles", // Component defined in backend/scripts/setupPostGIS.js
    "SyncStrapiContent": "component-styles", // Component defined in backend/scripts/syncStrapiContent.js
    "Update-strapi-institution": "component-styles", // Component defined in backend/scripts/update-strapi-institution.js
    "Update-strapi-locations": "component-styles", // Component defined in backend/scripts/update-strapi-locations.js
    "UpdateImgUrlAntik": "component-styles", // Component defined in backend/scripts/updateImgUrlAntik.js
    "App.example": "component-styles", // Component defined in backend/src/admin/app.example.js
    "Webpack.config.example": "component-styles", // Component defined in backend/src/admin/webpack.config.example.js
    "Geocode": "component-styles", // Component defined in backend/src/api/geocode/controllers/geocode.js
    "Museum-object": "component-styles", // Component defined in backend/src/api/museum-object/controllers/museum-object.js
    "Custom-routes": "component-styles", // Component defined in backend/src/api/museum-object/routes/custom-routes.js
    "Stats": "component-styles", // Component defined in backend/src/api/stats/controllers/stats.js
    "Webhook": "component-styles", // Component defined in backend/src/api/webhook/controllers/webhook.js
    "CREATE": "component-styles", // Component defined in backend/src/index.js
    "Components.d": "component-styles", // Component defined in backend/types/generated/components.d.ts
    "ContentTypes.d": "component-styles", // Component defined in backend/types/generated/contentTypes.d.ts
    "GET": "component-styles", // Component defined in frontend/app/api/generate-blurhash/route.ts
    "PATCH": "component-styles", // Component defined in frontend/app/api/proxy/corrections/[id]/route.ts
    "OPTIONS": "component-styles", // Component defined in frontend/app/api/webhook/strapi/route.ts
    "ObjectPage": "min-h-screen bg-background sticky top-0 z-50 border-b", // Component defined in frontend/app/artifact/[id]/page.tsx
    "RootLayout": "component-styles", // Component defined in frontend/app/layout.tsx
    "Loading": "component-styles", // Component defined in frontend/app/loading.tsx
    "MapLayout": "h-screen flex flex-col bg-white overflow-hidden flex-1", // Component defined in frontend/app/map/layout.tsx
    "MapPage": "flex h-full w-full items-center justify-center bg-white", // Component defined in frontend/app/map/page.tsx
    "RootPage": "component-styles", // Component defined in frontend/app/page.tsx
    "ArcDetailPage": "max-w-6xl mx-auto px-5 py-4 mb-4 flex", // Component defined in frontend/app/research/arc/[slug]/page.tsx
    "CollectionDetailPage": "max-w-5xl mx-auto px-5 py-4 mb-4 text-amber-500", // Component defined in frontend/app/research/collection/[slug]/page.tsx
    "ResearchLayout": "min-h-screen bg-white flex flex-col sticky top-0", // Component defined in frontend/app/research/layout.tsx
    "ResearchPage": "max-w-5xl mx-auto px-5 py-4 flex items-center", // Component defined in frontend/app/research/page.tsx
    "ResolversLayout": "resolver-dashboard-root", // Component defined in frontend/app/resolvers/layout.tsx
    "ResolversPage": "component-styles", // Component defined in frontend/app/resolvers/page.tsx
    "BackButton": "gap-2 h-4 w-4", // Component defined in frontend/components/back-button.tsx
    "BlurhashImage": "component-styles", // Component defined in frontend/components/blurhash-image.tsx
    "ClientMapLibreCSS": "component-styles", // Component defined in frontend/components/client-maplibre-css.tsx
    "FacetedFilter": "border-b border-border/50 last:border-b-0 pb-2 last:pb-0 w-full", // Component defined in frontend/components/faceted-filter.tsx
    "Index": "h-4 w-4", // Component defined in frontend/components/icons/index.tsx
    "ImageGallery": "shadow-lg h-8 w-8 h-4 w-4 gallery-image-bg", // position:fixed, top:0, left:0 (frontend/components/image-gallery.tsx)
    "LazyImage": "relative overflow-hidden", // Component defined in frontend/components/lazy-image.tsx
    "V3CommandPalette": "fixed inset-0 z-[80] bg-black/25 backdrop-blur-[2px] flex", // background:step.type === origin_country ? #3b82f6 (frontend/components/map/command-palette.tsx)
    "MapView": "w-full h-full flex items-center justify-center bg-red-50", // left:hoveredArc.x + 10, top:hoveredArc.y + 10, maxWidth:300px (frontend/components/map/map-view.tsx)
    "ObjectPanel": "h-full flex flex-col flex-shrink-0 items-center justify-center", // touchAction:none (frontend/components/map/object-panel.tsx)
    "MapLibreCSS": "component-styles", // Component defined in frontend/components/maplibre-css.tsx
    "ObjectGrid": "flex flex-col justify-center items-center h-full p-4", // Component defined in frontend/components/object-grid.tsx
    "ObjectList": "flex flex-col gap-3 justify-center items-center h-full", // Component defined in frontend/components/object-list.tsx
    "Index": "component-styles", // Component defined in frontend/components/resolver-dashboard/index.ts
    "StatusChip": "h-[4px] bg-secondary rounded-full flex-1 overflow-hidden flex", // Component defined in frontend/components/resolver-dashboard/institution-detail.tsx
    "ResolverDashboard": "h-screen flex flex-col items-center justify-center bg-background", // Component defined in frontend/components/resolver-dashboard/resolver-dashboard.tsx
    "ResolverList": "w-[260px] flex-shrink-0 border-r border-border bg-background flex", // Component defined in frontend/components/resolver-dashboard/resolver-list.tsx
    "RightPanel": "w-[240px] flex-shrink-0 border-l border-border bg-background flex", // Component defined in frontend/components/resolver-dashboard/right-panel.tsx
    "TopBar": "flex items-center px-5 h-11 border-b border-border", // Component defined in frontend/components/resolver-dashboard/topbar.tsx
    "Types": "component-styles", // Component defined in frontend/components/resolver-dashboard/types.ts
    "Use-resolver-data": "component-styles", // Component defined in frontend/components/resolver-dashboard/use-resolver-data.ts
    "ThemeProvider": "component-styles", // Component defined in frontend/components/theme-provider.tsx
    "Accordion": "flex h-4 w-4 shrink-0 transition-transform duration-200", // Component defined in frontend/components/ui/accordion.tsx
    "AlertDialog": "component-styles", // Component defined in frontend/components/ui/alert-dialog.tsx
    "Alert": "component-styles", // Component defined in frontend/components/ui/alert.tsx
    "AspectRatio": "component-styles", // Component defined in frontend/components/ui/aspect-ratio.tsx
    "Avatar": "component-styles", // Component defined in frontend/components/ui/avatar.tsx
    "Badge": "component-styles", // Component defined in frontend/components/ui/badge.tsx
    "Breadcrumb": "h-4 w-4 sr-only", // Component defined in frontend/components/ui/breadcrumb.tsx
    "Button": "component-styles", // Component defined in frontend/components/ui/button.tsx
    "Calendar": "h-4 w-4", // Component defined in frontend/components/ui/calendar.tsx
    "Card": "component-styles", // Component defined in frontend/components/ui/card.tsx
    "CarouselContext": "overflow-hidden h-4 w-4 sr-only", // Component defined in frontend/components/ui/carousel.tsx
    "THEMES": "grid gap-1.5 text-muted-foreground font-mono font-medium tabular-nums", // backgroundColor:item.color (frontend/components/ui/chart.tsx)
    "Checkbox": "h-3 w-3", // Component defined in frontend/components/ui/checkbox.tsx
    "Collapsible": "component-styles", // Component defined in frontend/components/ui/collapsible.tsx
    "Command": "overflow-hidden p-0 shadow-lg [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:font-medium [&_[cmdk-group-heading]]:text-muted-foreground", // Component defined in frontend/components/ui/command.tsx
    "ContextMenu": "ml-auto h-4 w-4 absolute left-2 flex", // Component defined in frontend/components/ui/context-menu.tsx
    "Dialog": "absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background", // Component defined in frontend/components/ui/dialog.tsx
    "Drawer": "mx-auto mt-4 h-2 w-[100px] rounded-full bg-muted", // Component defined in frontend/components/ui/drawer.tsx
    "DropdownMenu": "ml-auto absolute left-2 flex h-3.5 w-3.5", // Component defined in frontend/components/ui/dropdown-menu.tsx
    "Form": "component-styles", // Component defined in frontend/components/ui/form.tsx
    "HoverCard": "component-styles", // Component defined in frontend/components/ui/hover-card.tsx
    "InputOTP": "pointer-events-none absolute inset-0 flex items-center justify-center", // Component defined in frontend/components/ui/input-otp.tsx
    "Input": "component-styles", // Component defined in frontend/components/ui/input.tsx
    "Label": "component-styles", // Component defined in frontend/components/ui/label.tsx
    "MenubarMenu": "ml-auto h-4 w-4 absolute left-2 flex", // Component defined in frontend/components/ui/menubar.tsx
    "NavigationMenu": "relative top-[1px] ml-1 h-3 w-3 transition", // Component defined in frontend/components/ui/navigation-menu.tsx
    "Pagination": "h-4 w-4 sr-only", // Component defined in frontend/components/ui/pagination.tsx
    "Popover": "component-styles", // Component defined in frontend/components/ui/popover.tsx
    "Progress": "h-full w-full flex-1 bg-primary transition-all", // Component defined in frontend/components/ui/progress.tsx
    "RadioGroup": "flex items-center justify-center h-2.5 w-2.5 fill-current", // Component defined in frontend/components/ui/radio-group.tsx
    "ResizablePanelGroup": "z-10 flex h-4 w-3 items-center justify-center", // Component defined in frontend/components/ui/resizable.tsx
    "ScrollArea": "h-full w-full rounded-[inherit] relative flex-1 rounded-full", // Component defined in frontend/components/ui/scroll-area.tsx
    "Select": "h-4 w-4 opacity-50 absolute left-2 flex", // Component defined in frontend/components/ui/select.tsx
    "Separator": "component-styles", // Component defined in frontend/components/ui/separator.tsx
    "Sheet": "absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background", // Component defined in frontend/components/ui/sheet.tsx
    "SidebarContext": "w-[--sidebar-width] bg-sidebar p-0 text-sidebar-foreground [&>button]:hidden flex", // Component defined in frontend/components/ui/sidebar.tsx
    "Skeleton": "component-styles", // Component defined in frontend/components/ui/skeleton.tsx
    "Slider": "relative h-2 w-full grow overflow-hidden rounded-full", // Component defined in frontend/components/ui/slider.tsx
    "Toaster": "toaster group", // Component defined in frontend/components/ui/sonner.tsx
    "Spinner": "component-styles", // Component defined in frontend/components/ui/spinner.tsx
    "Switch": "component-styles", // Component defined in frontend/components/ui/switch.tsx
    "Table": "relative w-full overflow-auto", // Component defined in frontend/components/ui/table.tsx
    "Tabs": "component-styles", // Component defined in frontend/components/ui/tabs.tsx
    "Textarea": "component-styles", // Component defined in frontend/components/ui/textarea.tsx
    "ToastProvider": "h-4 w-4", // Component defined in frontend/components/ui/toast.tsx
    "Toaster": "bg-white text-black border border-gray-200 shadow-md grid", // Component defined in frontend/components/ui/toaster.tsx
    "ToggleGroupContext": "component-styles", // Component defined in frontend/components/ui/toggle-group.tsx
    "Toggle": "component-styles", // Component defined in frontend/components/ui/toggle.tsx
    "TooltipProvider": "component-styles", // Component defined in frontend/components/ui/tooltip.tsx
    "Use-mobile": "component-styles", // Component defined in frontend/components/ui/use-mobile.tsx
    "Use-toast": "component-styles", // Component defined in frontend/components/ui/use-toast.ts
    "UnifiedSearchBox": "relative h-3.5 w-3.5 animate-spin rounded-full border-2", // Component defined in frontend/components/unified-search-box.tsx
    "Use-arc-worker": "component-styles", // Component defined in frontend/hooks/use-arc-worker.ts
    "Use-geospatial-data": "component-styles", // Component defined in frontend/hooks/use-geospatial-data.ts
    "Use-media-query": "component-styles", // Component defined in frontend/hooks/use-media-query.ts
    "Use-spatial-documents": "component-styles", // Component defined in frontend/hooks/use-spatial-documents.ts
    "Use-unified-search": "component-styles", // Component defined in frontend/hooks/use-unified-search.ts
    "Components": "h-6 w-6 h-8 w-8 w-4 h-4", // Component defined in frontend/lib/design-system/components.ts
    "Tailwind.config.tokens": "component-styles", // Component defined in frontend/lib/design-system/tailwind.config.tokens.ts
    "Tokens": "h-4 w-4", // Component defined in frontend/lib/design-system/tokens.ts
    "Pmtiles-shim": "component-styles", // Component defined in frontend/lib/pmtiles-shim.ts
    "Protomaps-dark-style": "component-styles", // Component defined in frontend/lib/protomaps-dark-style.ts
    "Utils": "component-styles", // Component defined in frontend/lib/utils.ts
    "Lodash-debounce.d": "component-styles", // Component defined in frontend/lodash-debounce.d.ts
    "Next-env.d": "component-styles", // Component defined in frontend/next-env.d.ts
    "Next.config": "component-styles", // Component defined in frontend/next.config.js
    "Tailwind.config": "component-styles", // Component defined in frontend/tailwind.config.js
    "Arc-types": "component-styles", // Component defined in frontend/workers/arc-types.ts
    "Arc-worker": "component-styles", // Component defined in frontend/workers/arc-worker.ts
    "Tokens": "component-styles", // Component defined in tokens.ts
  },
  "templates": {},
  "pages": {},
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// Type-safe path accessor — full IDE autocomplete
// Usage:  getAura("colors.blue-500")  →  "#3B82F6"
// ─────────────────────────────────────────────────────────────────────────────

type Tokens = typeof tokens;

/** Every valid dot-path into the token tree, e.g. "colors.blue-500" */
export type TokenPath = {
  [K in keyof Tokens & string]: `${K}.${string & keyof Tokens[K]}`;
}[keyof Tokens & string];

/**
 * Access any design token by its dot-path with full type safety and autocomplete.
 * @example
 *   getAura("colors.blue-500")   // → "#3B82F6"
 *   getAura("spacing.spacing-4") // → "16px"
 */
export function getAura(path: TokenPath): string {
  const [cat, ...rest] = (path as string).split(".") as [string, ...string[]];
  const key = rest.join(".");
  const node = (tokens as Record<string, Record<string, string>>)[cat];
  return node?.[key] ?? "";
}
